name: Upload Python Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version number (e.g., 1.5.4)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine --verbose

    - name: Extract tag name if triggered by release
      if: github.event_name == 'release'
      run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Use manually provided version if triggered manually
      if: github.event_name == 'workflow_dispatch'
      run: echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV

    - name: Update version in setup.py
      run: sed -i "s/{{VERSION_PLACEHOLDER}}/${{ env.VERSION }}/g" setup.py

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --skip-existing dist/*
